name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # <--- Update ke v4

      - name: Setup Java
        uses: actions/setup-java@v4 # <--- Update ke v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun install

      - name: Build React App
        run: bun run build

      - name: Add Android Platform & Sync
        run: |
          bunx cap add android
          bunx cap sync

      - name: Build APK with Gradle
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4 # <--- INI PERBAIKAN UTAMANYA (v3 -> v4)
        with:
          name: titipin-app-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk